FORMAT: 1A
HOST: https://testapi.prioticket.com/s1

# PrioTicket Venue API

## Interface Specification

> Version: "B.2.3"

### Description

This document describes the interface between Prioticket systems and a Venue application. 

The API supports the following process:

+ Guests of Prioticket.com and its distribution partners can access museums and attractions (Venues) with an activated “pass_code”;
+ Upon Venue entry, the Venue’s scanner device scans a QR code. The Pass Code message starts with an unique domain name pattern. After recognizing the unique domain name pattern the Venue application will initiate a request to the Prioticket system to check if the unique Pass Code is valid;
+ In the response message Prioticket will send the status of the Pass Code (success/denied). If the Pass Code is accepted, the response message will also contain the related transaction details;
+ After successful receipt of the transaction information, the Venue will update their system with the transaction details and charge the ticket price to a Prioticket Account;
+ Prioticket will send a monthly report to the Venue with an overview of transactions and a tax invoice to settle the outstanding ticket payment.

The proceeding of this document describes the “Check Pass Code” method for integrating with the Prioticket system.

## Check Pass Code

Upon scan of a Pass Code by the Venue scanner, the Venue application will initiate an API request to the Prioticket system to get the status and transaction details from the Prioticket system.

Receiver = Prioticket

Initiator = Venue

The request data will be accepted in JSON format only and response data will also be in JSON format.
+ Test URL: https://testapi.prioticket.com/s1/check_passcode
+ Live URL: https://api.prioticket.com/s1/check_passcode

## Endpoints [/check_passcode]

### Check Passcode [POST]
Header: Initiator should send a “token” in the header of the message. The token is used for validation and to identify the partner. 

The token = Alphanumeric, 17 characters and would be in format (XXX-XXXX-XXXX-XXX). We will sent the token of the TEST and the LIVE environment in a separate emails.

+ Request (application/json)

    + Headers
    
                TOKEN : 5M1-T2T3-Y5N7-Q2S
                
    + Attributes
    
        + version: `B.2.3` (string, required) - B.2.3
        + pass_code: `http://qb.vg/0t-yfh` (string, required) - Full details of the scanned code. 
        Generated by Prioticket. Unique for each ticket. e.g. (http://qu.mu/AAA222)
        + venue_id: `35` (number, required) - Unique id of the venue where the pass is scanned.
        + location_id: `2` (string, optional) - An venue can have multiple locations. The ticket can depend on this location. 
        If location_id is left blank, the default location will be used to validate the pass_code.
        + transaction_ref: `123` (string, optional) - This is a transaction reference from the Venue that will be stored in Prioticket database for future use if needed and will be returned in the response message.
           
+ Response 200 (text/html)

    + Body

                {
                  "response_code": 1,
                  "message": "success",
                  "transaction_id": 310065,
                  "pass_code": "0t-yfh",
                  "currency": "EUR",
                  "distributor_ref": "150",
                  "venue_id": 35,
                  "venue_name": "Van Gogh Museum",
                  "entrance_date_time": "2016-12-07T12:04:27",
                  "total_amount": 65,
                  "transaction_ref": "",
                  "transaction_type": "Direct",
                  "ticket_info": [
                    {
                      "location_id": "",
                      "ticket_id": "96",
                      "ticket_name": "Van Gogh Museum Entry with Voucher Lane Access",
                      "ticket_plu": 101,
                      "ticket_ref": "",
                      "reservation": 0,
                      "reservation_id": 0,
                      "reservation_ref": "",
                      "valid_from": "",
                      "valid_till": "",
                      "number_of_users": 6,
                      "user_info": [
                        {
                          "ticket_type_id": 1,
                          "ticket_type_tag": "Adult",
                          "ticket_type_ref": "",
                          "user_age_group": "18-99",
                          "price_per_ticket": 15,
                          "tax_percentage": 6,
                          "tax_per_ticket": 0.85,
                          "ticket_type_option": [
                            {
                              "tto_id": 0,
                              "tto_ref": "",
                              "tto_price": 0,
                              "tto_tax_percentage": 0,
                              "tto_tax_amount": 0
                            }
                          ]
                        },
                        {
                          "ticket_type_id": 1,
                          "ticket_type_tag": "Adult",
                          "ticket_type_ref": "",
                          "user_age_group": "18-99",
                          "price_per_ticket": 15,
                          "tax_percentage": 6,
                          "tax_per_ticket": 0.85,
                          "ticket_type_option": [
                            {
                              "tto_id": 0,
                              "tto_ref": "",
                              "tto_price": 0,
                              "tto_tax_percentage": 0,
                              "tto_tax_amount": 0
                            }
                          ]
                        },
                        {
                          "ticket_type_id": 1,
                          "ticket_type_tag": "Adult",
                          "ticket_type_ref": "",
                          "user_age_group": "18-99",
                          "price_per_ticket": 15,
                          "tax_percentage": 6,
                          "tax_per_ticket": 0.85,
                          "ticket_type_option": [
                            {
                              "tto_id": 0,
                              "tto_ref": "",
                              "tto_price": 0,
                              "tto_tax_percentage": 0,
                              "tto_tax_amount": 0
                            }
                          ]
                        },
                        {
                          "ticket_type_id": 3,
                          "ticket_type_tag": "Child",
                          "ticket_type_ref": "",
                          "user_age_group": "1-3",
                          "price_per_ticket": 0,
                          "tax_percentage": 6,
                          "tax_per_ticket": 0,
                          "ticket_type_option": [
                            {
                              "tto_id": 0,
                              "tto_ref": "",
                              "tto_price": 0,
                              "tto_tax_percentage": 0,
                              "tto_tax_amount": 0
                            }
                          ]
                        },
                        {
                          "ticket_type_id": 3,
                          "ticket_type_tag": "Child",
                          "ticket_type_ref": "",
                          "user_age_group": "4-17",
                          "price_per_ticket": 10,
                          "tax_percentage": 6,
                          "tax_per_ticket": 0.57,
                          "ticket_type_option": [
                            {
                              "tto_id": 0,
                              "tto_ref": "",
                              "tto_price": 0,
                              "tto_tax_percentage": 0,
                              "tto_tax_amount": 0
                            }
                          ]
                        },
                        {
                          "ticket_type_id": 3,
                          "ticket_type_tag": "Child",
                          "ticket_type_ref": "",
                          "user_age_group": "4-17",
                          "price_per_ticket": 10,
                          "tax_percentage": 6,
                          "tax_per_ticket": 0.57,
                          "ticket_type_option": [
                            {
                              "tto_id": 0,
                              "tto_ref": "",
                              "tto_price": 0,
                              "tto_tax_percentage": 0,
                              "tto_tax_amount": 0
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }